services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: pdf-processing-app
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    network_mode: "host"
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack-main}"
    image: localstack/localstack:s3-latest
    ports:
      - "127.0.0.1:4566:4566"
    volumes:
      - "./init-s3.py:/etc/localstack/init/ready.d/init-s3.py"  

  # db:
  #   image: postgres:15.4
  #   container_name: otel-sentry-db
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_DB: postgres
  #   ports:
  #     - "5434:5432"
  #   volumes:
  #     - otel-sentry-db-data:/var/lib/postgresql/data

# volumes:
#   otel-sentry-db-data: