services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: pdf-processing-app
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    network_mode: "host"

  # db:
  #   image: postgres:15.4
  #   container_name: otel-sentry-db
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_DB: postgres
  #   ports:
  #     - "5434:5432"
  #   volumes:
  #     - otel-sentry-db-data:/var/lib/postgresql/data

# volumes:
#   otel-sentry-db-data: