version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: otel-sentry-app
    ports:
      - "8001:8001"
    env_file:
      - system_configs/.env
    depends_on:
      - db
    volumes:
      - .:/app

  db:
    image: postgres:15.4
    container_name: otel-sentry-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5434:5432"
    volumes:
      - otel-sentry-db-data:/var/lib/postgresql/data

volumes:
  otel-sentry-db-data: